#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

gitleaks dir . --redact --no-banner --config .gitleaks.toml
gitleaks git . --redact --no-banner --config .gitleaks.toml
